### ISSUE TITLE
Crash when adding the VL.IO.NDI dependency

### ISSUE THREAD

**Issue by sunep** [mhusinsky/VL.IO.NDI#3]
After installing VL.IO.NDI v0.2.1-alpha, gamma crash with the following messages when trying to add the NDI dependency to a blank patch:

error logs:
[VL.IO.NDI-error-2020.2.2.log](https://github.com/mhusinsky/VL.IO.NDI/files/5451722/VL.IO.NDI-error-2020.2.2.log)
[VL.IO.NDI-error-2020.3.3-0056.log](https://github.com/mhusinsky/VL.IO.NDI/files/5451723/VL.IO.NDI-error-2020.3.3-0056.log)

When opening the examples in the help browser, the little dot, that turns into a cross next to the link to the example patch, turns into a rotating ring that never stops rotating.

also [posted on the vvvv.org forum](https://discourse.vvvv.org/t/crash-when-adding-the-vl-io-ndi-dependency/18878)

**Comment by mhusinsky** [comment]
yes, this is a known issue for vvvv > 2020.2.1. 
VL.IO.NDI needs an update for these versions.

**Comment by joreg** [comment]
this should meanwhile be fixed. please reopen if you see the problem persist.
