### ISSUE TITLE
SourceSelector matches only 'SourceName', cannot select duplicate sources on different machines

### ISSUE THREAD

**Issue by TobyKLight** [mhusinsky/VL.IO.NDI#4]
There are three different name types for an NDI source, with some confusing overlap. 

'ComputerName' = Name of the computer eg "WindowsRender5" 
'SourceName' = Name of the source  eg  "Logitech Webcam C920"
'Name' = ComputerName + SourceName together eg "WindowsRender5 (Logitech Webcam C920)" 

Currently SourceSelector node only matches for SourceName.
This means that if two machines have a source with the same name then mismatches can occur.

This can easily happen as the NDI Capture utility takes 'SourceName' automatically from hardware device names. 
In my case I have multiple machines with a 'Logitech Webcam C920'

**Comment by mhusinsky** [comment]
indeed, this is a shortcoming in the SourceFinder that should be easy to fix. 
it's probably more appropriate to use the 'Name' in the form the base library provides (i.e. 'ComputerName (SourceName)' ). would you agree on that?

**Comment by TobyKLight** [comment]
I would agree, sounds good
