### ISSUE TITLE
Changing connection source on receiver machine crashes ndi source program

### ISSUE THREAD

**Issue by HydeNaut** [mhusinsky/VL.IO.NDI#6]
Hi @mhusinsky . Having this issue with Gamma 2021.4.3 where the send and receive demos work perfectly across a local network, but if I change the the source image the receiver gets (e.g. from 'VL.Source Async' to 'Desktop Capture' for example, or adding an extra receiving PC) the The Gamma sending patch crashes

For a craic I tried replacing the runtime with the newest (5.0.10.1) but it didn't improve this issue, so its something to do with the connection stage.

To reproduce this, run both the NDI screen capture and the Gamma Sending howTo patch. On a separate machine in the network, run the receiving patch. It should show both the sources. Change source getslice. The Sending Gamma will close down without an error.

**Comment by joreg** [comment]
please try latest version of the pack and re-open if this persists.

**Comment by HydeNaut** [comment]
Thanks Joreg
